package com.github.quizclash.domain;

public enum ScreenProviderType {
    ADD_USER, CHANGE_CATEGORY_SETTINGS, GAME_MODE, GAME_SETTINGS, LOCAL_MULTIPLAYER, MENU, REMOVE_USER, TRAINING, USER_MENU, WELCOME
}
